# Prompt: name@machine ~/some/path$
PS1='%n@%m %~$ '

# Always color ls and group directories
alias ls='ls --color=auto'

# ZSH keybinds
# list current binds: keybind
# list keymaps: keybind -l
# list keybinds for keymap: keybind -M keymap
# list all available commands: zle -al

#Delete
bindkey "^[[3~" delete-char
#Ctrl+R for history search
bindkey "^R" history-incremental-search-backward



# set terminal title to cwd
DISABLE_AUTO_TITLE="true"
function set_title_to_pwd() {
    echo -en "\e]2;$(pwd | sed "s/${HOME//\//\\/}/~/")"
}
autoload add-zsh-hook
add-zsh-hook chpwd set_title_to_pwd
set_title_to_pwd

# Make Vi mode transitions faster (in hundredths of a second)
KEYTIMEOUT=1

# change cursor based on vim keybind mode (normal/insert)
zle-keymap-select () {
    if [ $KEYMAP = vicmd ]; then
        printf "\033[2 q"
    else
        printf "\033[6 q"
    fi
}
zle -N zle-keymap-select
zle-line-init () {
    zle -K viins
    printf "\033[6 q"
}
zle -N zle-line-init

#enable vi keybinds. This should already be configured by nix but for
#compatibility with other systems set it again
bindkey -v

