if [[ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    . /nix/var/nix/profiles/default/etc/profile.d/nix.sh
fi

export PATH="$PATH:$HOME/.cargo/bin"

# Always color ls and group directories
alias ls='ls --color=auto'

# bind delete key
bindkey "^[[3~" delete-char

DISABLE_AUTO_TITLE="true"

# set terminal title to cwd
function set_title_to_pwd() {
    echo -en "\e]2;$(pwd | sed "s/${HOME//\//\\/}/~/")"
}

autoload add-zsh-hook
add-zsh-hook chpwd set_title_to_pwd
set_title_to_pwd

