#!/bin/sh -e

CONFIG="$1"
if [ -z "$CONFIG" ]; then
    echo "No config name given. Exiting"
    exit 1
fi
shift

SYSTEM="darwinConfigurations.$CONFIG.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "Starting build..."
nix --experimental-features 'nix-command flakes' build --max-jobs auto ".#$SYSTEM" "$@"

echo "Switching to new build..."
./result/sw/bin/darwin-rebuild switch --flake ".#$CONFIG" "$@"

echo "Cleaning up..."
unlink ./result

