" Setup for Vim. This is all default behavior in NeoVim
set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8

" key sequence timeouts
set timeoutlen=500
set ttimeoutlen=10

" search highlight options
set incsearch
set nohlsearch
if exists('&inccommand') " not supported in all versions
    set inccommand=split
endif
set cmdwinheight=20

" swap/backup/undo directories
set backup
set backupdir=~/.vim/backup//
set swapfile
set dir=~/.vim/swap//
set undofile
set undodir=~/.vim/undo//
set updatetime=100

" autoread from filesystem
set autoread

" undo history
set history=10000

" delete comment characters when joining lines
set formatoptions+=j

" default indentation options when not overridden by plugins
set autoindent
set expandtab
set shiftround
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent " Neovim turns this off in init.lua and uses treesitter instead

" wrap options
set nowrap

" interface options
set laststatus=2 " always show status bar
set scrolloff=0
set signcolumn=yes
set ruler
" set virtualedit=onemore " allow cursor to go past end of line

" window title
set title
set titlestring=%t%(\ %M%)%(\ \(%{expand(\"%:~:h\")}\)%)%a

" line numbers
set number
set relativenumber

" cursor line
set cursorline
set cursorlineopt=number

" colors
set termguicolors
set background=dark

" wildcard menu settings
set wildmenu
set wildmode=longest:full
set wildoptions=pum,tagfile,fuzzy

" remap arrow keys in wildcard menu
set wildcharm=<C-Z>
cnoremap <expr> <up> wildmenumode() ? "\<left>" : "\<up>"
cnoremap <expr> <down> wildmenumode() ? "\<right>" : "\<down>"
cnoremap <expr> <left> wildmenumode() ? "\<up>" : "\<left>"
cnoremap <expr> <right> wildmenumode() ? " \<bs>\<C-Z>" : "\<right>"

" enable spellchecking
set spell
set spelllang=en
set spelloptions=camel " spellcheck CamelCase words

" Disable highlighting of rare words, regional words, and incorrect
" capitalization. ]s and [s will still jump to them.
function HlOnlySpellBad()
    highlight clear SpellRare
    highlight clear SpellCap
    highlight clear SpellLocal
endfunction
autocmd BufNew * call HlOnlySpellBad()

" Install some builtin Vim plugins
packadd cfilter
packadd justify
packadd matchit

" Change hotkey to edit in command mode
set cedit=\<C-E>

