set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8

" key sequence timeout
set timeoutlen=3000

" search options
set incsearch
set nohlsearch

" vim directories
" set noswapfile
set backupdir=~/.vim/backup//
set dir=~/.vim/swap//
set undodir=~/.vim/undo//
set updatetime=500

" autoread from filesystem
set autoread

" undo history
set history=10000

" delete comment characters when joining lines
set formatoptions+=j

" default indentation options when not overriden by plugins
set autoindent
set expandtab
set shiftround
set tabstop=4
set shiftwidth=4
set softtabstop=4
" set smartindent

" wrap options
set nowrap

" interface options
set laststatus=2 " always show status bar 
set scrolloff=5
set signcolumn=yes
set ruler
" set virtualedit=onemore " allow cursor to go past end of line

" window title
set title
set titlestring=%t%(\ %M%)%(\ \(%{expand(\"%:~:h\")}\)%)%a

" line numbers
set number
set relativenumber

" cursor line
set cursorline
set cursorlineopt=number

" colors
set termguicolors
set background=dark

" allow dashes in filenames
set isfname-=-

" wildcard menu settings
set wildmenu
set wildmode=longest:full
set wildoptions=pum,tagfile,fuzzy

" remap arrow keys in wildcard menu
set wildcharm=<C-Z>
cnoremap <expr> <up> wildmenumode() ? "\<left>" : "\<up>"
cnoremap <expr> <down> wildmenumode() ? "\<right>" : "\<down>"
cnoremap <expr> <left> wildmenumode() ? "\<up>" : "\<left>"
cnoremap <expr> <right> wildmenumode() ? " \<bs>\<C-Z>" : "\<right>"

